global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']  # Scrape the NGINX container for metrics
    metrics_path: /status  # Path to NGINX metrics in Prometheus format
