# detection/models.py

from django.db import models

class ThreatData(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    threat_level = models.FloatField()  # A score generated by your AI model
    description = models.CharField(max_length=255)  # Text description of the threat
    source_ip = models.GenericIPAddressField()  # Source IP of the threat
    processed = models.BooleanField(default=False)  # Whether the threat has been processed

    def __str__(self):
        return f"{self.description} ({self.threat_level}) - {self.source_ip}"
