# Generated by Django 5.1.2 on 2024-10-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('threat_level', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('source_ip', models.GenericIPAddressField()),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
