apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\karan\kompose\kompose.exe convert -o ./kubernetes-config/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: django-3
  name: django-3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: django-3
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\karan\kompose\kompose.exe convert -o ./kubernetes-config/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: django-3
    spec:
      containers:
        - args:
            - sh
            - -c
            - |
              python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              daphne -b 0.0.0.0 -p 8000 ThreatDetection.asgi:application
          image: django-3
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8000/health
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          name: django-3
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "1073741824"
            requests:
              cpu: 500m
              memory: "536870912"
          volumeMounts:
            - mountPath: /app
              name: django-3-cm0
            - mountPath: /app/static
              name: static-volume
            - mountPath: /app/media
              name: media-volume
      restartPolicy: Always
      volumes:
        - configMap:
            name: django-3-cm0
          name: django-3-cm0
        - name: static-volume
          persistentVolumeClaim:
            claimName: static-volume
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-volume
