apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\karan\kompose\kompose.exe convert -o ./kubernetes-config/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: django-2
  name: django-2
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 8000
  selector:
    io.kompose.service: django-2
