apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\karan\kompose\kompose.exe convert -o ./kubernetes-config/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\karan\kompose\kompose.exe convert -o ./kubernetes-config/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - image: nginx:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost/
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "536870912"
            requests:
              cpu: 200m
              memory: "268435456"
          volumeMounts:
            - mountPath: /app/static
              name: static-volume
            - mountPath: /app/media
              name: media-volume
            - mountPath: /var/log/nginx
              name: nginx-cm3
      restartPolicy: Always
      volumes:
        - name: static-volume
          persistentVolumeClaim:
            claimName: static-volume
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-volume
        - configMap:
            name: nginx-cm3
          name: nginx-cm3
