apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\karan\kompose\kompose.exe convert -o ./kubernetes-config/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nginx-prometheus-exporter
  name: nginx_prometheus_exporter
spec:
  ports:
    - name: "9113"
      port: 9113
      targetPort: 9113
  selector:
    io.kompose.service: nginx-prometheus-exporter
