apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\karan\kompose\kompose.exe convert -o ./kubernetes-config/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: redis-exporter
  name: redis_exporter
spec:
  ports:
    - name: "9121"
      port: 9121
      targetPort: 9121
  selector:
    io.kompose.service: redis-exporter
