apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\karan\kompose\kompose.exe convert -o ./kubernetes-config/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: redis-exporter
  name: redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-exporter
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\karan\kompose\kompose.exe convert -o ./kubernetes-config/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: redis-exporter
    spec:
      containers:
        - args:
            - --redis.addr=redis:6379
          image: oliver006/redis_exporter
          name: redis-exporter
          ports:
            - containerPort: 9121
              protocol: TCP
      restartPolicy: Always
